### ISSUE TITLE
we need a logo

### ISSUE THREAD

**Issue by zwetan** [as3lang/www.as3lang.org#2]
## Why ?

Take two example
- [dart lang](https://www.dartlang.org/logos/)
- [HTML5](http://www.w3.org/html/logo/)

to communicate about AS3 and promote it I believe we should take a similar approach,
yeah it's marketing, yeah it's like building a brand, but because at the end of the day we want to "sell" that technology we need to make it "sexy" and that start with a logo.

"as is" we can not really re-use Flash or AIR logos, they are first the responsibility of Adobe (if they decide to promote them), and second you know how much the word "flash" got a bad rap by the media etc.

that does not mean we will not promote flash and AIR, but in itself if we start by "flash can do this ..."
it is almost like the other party automatically shut down, our approach will be more about "here look what we built with actionscript 3.0" and then "oh yeah we published on mobile with AIR" etc.
## Goal

Find a logo that convey the "Actionscript 3.0" or "AS3" brand so we (developers, designers still using Flash, AIR etc. to build products, apps, games, etc.) we could all rally behind it.

So, yeah, that's a bit abstract; historically we have this `{AS}³`

indeed when the language name is "ruby" it is easier to come with a nice [ruby gem logo](https://www.ruby-lang.org/en/),
in our case not so much.

imho here few important things
- keeping the **3**, we don't do AS1 or AS2, we do AS3  
  but if the same logo can decline with 2 and 1 that's a bonus
- it should work on small size (think favicon, awesome font, etc.)
- it should work in one color with maybe various transparency value  
  (see [Burrrn B](http://www.burrrn.com/500))
- it will probably use a red main color to connect with Flash / AIR
- it will be nicer if it works in vector

How look like a great logo (in my opinion)?

![Auricom logo](http://static.giantbomb.com/uploads/original/0/546/332816-auricom2.jpg)
## Preview

If you want to submit a logo please send a PNG (or GIF or JPG) of at least 64x64,
ideally something bigger like 256x256 or 512x512 preferred.

I will post it on twitter on the @as3lang and ppl will vote / give their opinion.

If there are many submissions, I will put a page on as3lang.org to show them all side by side.

For all the rest, we'll look into the details later or you can ask questions in this issue.

**Comment by mariommoreno** [comment]
Just a proposal. :)
 I don't think we have to deny the Flash origins of the language.

![as3-logo](https://cloud.githubusercontent.com/assets/2721843/8778354/bff1cdf4-2efd-11e5-93ba-1715be8978c3.png)

**Comment by YopSolo** [comment]
![as3-logo](https://cloud.githubusercontent.com/assets/1012515/8786023/eea28cc8-2f2b-11e5-862d-981efb2674f6.png)

**Comment by blackjyn** [comment]
![as31](https://cloud.githubusercontent.com/assets/6046191/8794651/a89d652a-2faf-11e5-9c30-9af03bb1b97f.png)

**Comment by blackjyn** [comment]
![as32](https://cloud.githubusercontent.com/assets/6046191/8794682/fedbbda6-2faf-11e5-86fe-ae65625abd33.png)

**Comment by nukadelic** [comment]
![as3 logos](https://cloud.githubusercontent.com/assets/6582633/8822485/1aa7ec5e-30a9-11e5-9fa7-19be78ced810.png)

**Comment by igoramendola** [comment]
![as3-b_](https://cloud.githubusercontent.com/assets/13456523/8834145/3124eba2-3078-11e5-84ff-341714435483.png) 
![as3-a_](https://cloud.githubusercontent.com/assets/13456523/8834146/313591aa-3078-11e5-8f29-caad92144067.png)

**Comment by codeandvisual** [comment]
![as3_logo_4](https://cloud.githubusercontent.com/assets/3396260/8842075/0619e8a6-3139-11e5-8e5c-5abec79a5aa9.png)

**Comment by zwetan** [comment]
based on all proposals, taking a bit of this a bit of that, etc.

inspired by the Adobe logo redesign in CS3
http://veerle-v2.duoh.com/blog/comments/the_new_adobe_icons_and_branding/

and inspired by the flash design here
https://www.behance.net/gallery/24661125/Flash-Flat-Free

here what I think can work everywhere
![as3lang_logotype](https://cloud.githubusercontent.com/assets/236154/9021450/cbf6bd00-3842-11e5-8eb8-a2a392d7546a.png)
